- .travis.yml
This fixes a typo in the `.travis.yml` that was breaking all linux builds. All pass again after this fix.
> Fix travis linux build

- appveyor.yml
Define a CMAKE_PREFIX_PATH and let CMake look into "include" and "lib"
subdirectories itself. Only ZLIB_LIBRARY is still explicitely passed as it uses
a name which is not included in FindZLIB.cmake.
> use less variables when defining the test environment

- CMakeLists.txt
All components are unconditionally set before, so there is no need to put the
version string in the cache. Doing so would pin the version string in case
someone updates the source without deleting the build directory.
> do not cache the version string

- test/t/util/test_file.cpp
When running tests on Windows I have last debug assertion windows in test_file.cpp:
https://www.dropbox.com/s/yqv6jrow0ab4fj7/2015-10-09%2012_30_35-Microsoft%20Visual%20C%2B%2B%20Runtime%20Library.png?dl=0
for tests with non-existing file descriptor. According to https://msdn.microsoft.com/en-us/library/a9yf33zb.aspx mentioned in the code, `_CrtSetReportMode(_CRT_ASSERT, 0)` is needed to prevent this crash.
(now all the debug tests pass)
> remove assertion messageboxes in tests on Windows

- include/osmium/memory/buffer.hpp
- include/osmium/memory/item_iterator.hpp
The previous implementation would call `m_full` when a reservation request would cause the buffer to overflow, but assumed that an empty buffer could hold the requested size without checking it. If the buffer is small, then this might not be the case, and the buffer would expand into potentially unallocated memory.
This implementation first tries to empty the buffer by calling `m_full` and then re-checks the size, which allows the buffer to grow if `m_auto_grow` is set appropriately.
The `m_full` and `m_auto_grow` members should be swapped in `swap`, which is fixed here. Finally, the behaviour of `item_iterator`'s `bool` conversion is updated to match the checks done before dereference, which makes it easier to check if the iterator will fail before dereferencing it.
> Try to flush the Buffer, then also try to grow

- test/data-tests/CMakeLists.txt
Using find_package causes the test to fail unless the headers are installed, but we only need to run a script.
> The multipolygon test only needs the ruby interpreter

- include/osmium/tags/regex_filter.hpp
- test/t/tags/test_filter.cpp
Added a tag `match_key<std::regex>` for regexp key filters `osmium::tags::Filter<std::regex>`
> Add match_key<std::regex> tag

- include/osmium/visitor.hpp
- test/t/io/test_reader.cpp
For #180. Perfectly forwards handlers in order to let the user specify one-off handlers in place, think:
osmium::apply(reader, StreamPrinter{cout}};
@joto I _think_ there may be other locations in the code base where perfectly forwarding should be done. For this changeset I specifically only changed what is needed to make this use-case work.
> Implements rvalue handler support for apply, resolves #180.

- include/osmium/util/file.hpp
By default, `windows.h` includs `winsock.h`.
Later, `osmium/io/detail/pbf.hpp` includes `winsock2.h` leading to compilation errors due to conflicting WinSock versions.
Alternatively, user has to carefully include libosmium headers to ensure `osmium/io/detail/pbf.hpp` comes before `osmium/util/file.hpp`.
> Prevent windows.h from including winsock.h

- include/osmium/util/file.hpp
- include/osmium/util/string_matcher.hpp
On Windows there are many build warnings, some of them are reasonable.
First fix is about macro redefinition (in Windows-only code), second is char*-to-bool conversion:
is
```c++
return std::strstr(test_string, m_str.c_str()) != nullptr;
```
better for returning bool than
```c++
return std::strstr(test_string, m_str.c_str());
```
? 
(example: 48 to 12 warnings in osmium_tool)
> Reduce number of warnings

- CMakeLists.txt
- appveyor.yml
- build-appveyor.bat
- cmake/FindOsmium.cmake
There are many some unrelated warnings and garbage messages that could be easily fixed for Visual Studio builds:
- There are many missing .pdb files in dependencies back (they are too big to carry), so there were about 500 extra warnings
- There are buggy VS messages about Xamaring targets, better to have a workaround until they fix Visual Studio http://help.appveyor.com/discussions/problems/4569-the-target-_convertpdbfiles-listed-in-a-beforetargets-attribute-at-c-does-not-exist-in-the-project-and-will-be-ignored
- To disable .pdb-related warning I had to enable using USUAL_LINK_OPTIONS in RELWITHDEBUGINFO config. Hope it is OK (USUAL_LINK_OPTIONS="" on non-MS)
- Warning C4503 (name longer than 4096 symbols truncated) is too popular in libosmium (171 instances).
I thing no one will …
> Reduce number of warnings on Appveyor

- .gitignore
The `_` prefix is handy to easily distinguish build folders it in directory listings, especially if one juggles multiple of `_build.32`, `_build.64`, `_build.clang`, etc.
> Ignore _build* directories

- include/osmium/io/detail/debug_output_format.hpp
- include/osmium/io/detail/input_format.hpp
- include/osmium/io/detail/opl_output_format.hpp
- include/osmium/io/detail/output_format.hpp
- include/osmium/io/detail/pbf_input_format.hpp
- include/osmium/io/detail/pbf_output_format.hpp
- include/osmium/io/detail/xml_output_format.hpp
- include/osmium/io/reader.hpp
- include/osmium/io/writer.hpp
- include/osmium/thread/pool.hpp
- test/data-tests/testdata-xml.cpp
- test/t/io/test_reader.cpp
- test/t/io/test_writer.cpp
- test/t/io/test_writer_with_mock_encoder.cpp
- test/t/thread/test_pool.cpp
Enable use of user-provided `thread::Pool` instance
`Pool` instance can be configured with user-specified number of threads and passed to `Reader` and `Writer` as optional argument of constructors.
If no `Pool` is specified, default instance is used and configured with number of threads based on actual number of cores on the system.
Advantages:
* Allows to use `Pool` configured with user-preferred number of threads.
* If libosmium used in a shared library, this helps to prevent potential deadlock during Pool shutdown at (after) shared library unloading (see #213 for details).
------
* Compiled with GCC 7.1.0 and passed all tests on Ubuntu Linux (complete test suite)
* Compiled with VS2017 and run using custom sample reader/writer (XML, PBF) app
> Enable use of user-provided thread::Pool instance

- build-appveyor.bat
Local builds failed because of the hard coded reference to AppVeyor's custom build logger: `Appveyor.MSBuildLogger.dll`
Local builds work again and behavior on AppVeyor is as was, eg see messages here:
https://ci.appveyor.com/project/Mapbox/libosmium/build/1.0.744/job/b0nkg6jxgii9x26h/messages
> Use Appveyor.MSBuildLogger on AppVeyor only

- include/osmium/osm/timestamp.hpp
- include/osmium/util/file.hpp
- include/osmium/util/memory_mapping.hpp
As mentioned in https://github.com/osmcode/libosmium/issues/224 , both _WIN32 and _MSC_VER are used in the code to support Windows build. On Visual Studio the compiler is different and needs more workarounds (no POSIX library function). Basic _WIN32 checks are used for Unx-specific or non-C++-standard functions, like file IO and memory mapping.
However, some checks were incorrectly placed and GCC compiler on Windows (working as part of MSYS2 environment) failed to build libosmium tests and examples. Here is my attemt to fix it (Microsoft compatibility is not broken, just checked, all tests pass).
> Make libosmium compatible with MSYS2 (gcc 7.2.0 on Windows)

- appveyor.yml
- build-msys2.bat
- cmake/FindGem.cmake
Following https://github.com/osmcode/libosmium/issues/224  and https://github.com/osmcode/libosmium/pull/226
Here is the build on Windows with latest MinGW compiler provided by MSYS2 project. The dependencies are also provied and downloaded as binary pacakages (may be updating, versions are not fixed).
I have also found a source of minor problem with not-finding json ruby gem - gem executable was called gem.cmd and was not found with FindGem.cmake.
With current version of MSYS2 packages all the tests should pass.
> Add Msys2 building appveor

- test/data-tests/CMakeLists.txt
- test/data-tests/run-testdata-multipolygon.cmake
Noticed that for MSVC builds the testsdata-multipolygon test failed (previously it was not run because of gem finding bug). The reason was /Release/ folder in test executable path (tests are run with `ctest -VV -C Release` but our manual code did not use that rare option). So the solution proposed is to pass EXECUTABLE parameter to run-testdata-multipolygon.cmake . Should make appveyor even more happy :)
> Fix testdata-multipolygon test on Windows (executable path differs)

- cmake/FindOsmium.cmake
- include/osmium/io/detail/pbf.hpp
- include/osmium/io/detail/pbf_input_format.hpp
- include/osmium/io/detail/pbf_output_format.hpp
- test/data-tests/CMakeLists.txt
- test/data-tests/run-testdata-multipolygon.cmake
Many warnings and previous build problems were related to winsock2 library we used. But currently the only place where it is needed is byte order conversion https://github.com/osmcode/libosmium/blob/381cf92723a1fab5b1fc74fcb8f0ad89d73b7274/include/osmium/io/detail/pbf_output_format.hpp#L188
Now that we have protozero library, this can easily be avoided, at least on Windows (little-endian only).
> No winsock dependency

- include/osmium/geom/geojson.hpp
- include/osmium/geom/wkt.hpp
- test/t/geom/test_geojson.cpp
- test/t/geom/test_wkt.cpp
- test/t/geom/wnl_helper.hpp
I was trying to use these classes in another project and noticed there did not seem to be an implementation of the various Polygon handler methods for the WKT and GeoJSON writers. I'm afraid I don't have an exact example of the error this produces available any more but roughly the WKT or GeoJSON writer would error out because there is no polygon_start implementation included. I added the necessary methods for this along with test cases to cover them.
It's worth noting that the one I added so far is a fairly naive Polygon implementation in that it does not expect any of the geometries to include interior rings. However based on my understanding of how OSM represents these geometries I think this is OK since those would always be handled as Areas and thus get serialized as MultiPolygons …
> Add polygon implementation for WKT and GeoJSON Geometry Factories

- include/osmium/osm/object.hpp
- include/osmium/osm/object_comparisons.hpp
- test/t/osm/test_object_comparisons.cpp
Changes:
* Remove object_order_type_id_reverse_version_without_timestamp
* Ignore the timestamp when comparing objects if one object does not have a valid timestamp. Invalid timestamps are internally stored as 0 and lead to wrong results when `operator<` is called. This makes some fixes in Osmium Tool (https://github.com/osmcode/osmium-tool/pull/87, https://github.com/osmcode/osmium-tool/pull/88, https://github.com/osmcode/osmium-tool/pull/94) easier because their code changes can be rejected and only their new unit tests merged into master.
> Object comparison without timestamp

- cmake/FindOsmium.cmake
> Make sure -stdlib=libc++ is only set on Mac when compiling with Clang

- include/osmium/osm/changeset.hpp
- include/osmium/osm/relation.hpp
Detected while playing around with a new clang-tidy check that is in development. :grin:
> Minor: Wrong order of qualifiers

- test/t/relations/missing_members.osm
- test/t/relations/test_relations_manager.cpp
This unit test checks the following statement from https://osmcode.org/libosmium/manual.html#working-with-relations:
> The pointers returned from the get_member_* functions will be nullptr if the member is not available.
@joto I decided to create `AnyRM` to explicitly state that I want to have all members. Or shall I intentionally rely on the current implemention in `osmium::relations::RelationsManager` and use `EmptyRM` instead.
> Test that RelationsManagerBase::get_member_object returns nullptr

- test/t/index/test_id_to_location.cpp
I was looking into the implementation of the FlexMem class today and looked how location indexes are tested.
SparseMmapArray is not tested in the same file where all other index types are tested (but it is covered by data tests). I added to be consistent.
In addition, I fixed an obvious typo in the same file.
> Add test for SparseMmapArray, fix typo

- build-msys2.bat
The fix for gdal is available upstream and references the correct json-c dll.
The workaround (until reported/fixed upstream) provides a spatialite dependency: readline 7.
> AppVeyorCI: Fix MSYS2 build

- include/osmium/builder/attr.hpp
Looks like the names for these arguments are swapped, which could lead to confusion and subtle bugs.
> Fix location attr variable name typo

- include/osmium/io/detail/pbf_decoder.hpp
When parsing lat from pbf densenode,
I noticed lat is also parsed using convert_pbf_coordinate which also using m_lon_offset.
Per https://wiki.openstreetmap.org/wiki/PBF_Format
`latitude = .000000001 * (lat_offset + (granularity * lat))
longitude = .000000001 * (lon_offset + (granularity * lon))`
latitude should be calculated from lat_offset
> fix parsing lat bug from pbf densenode

- test/examples/t/change_tags/CMakeLists.txt
I've been seeing intermittent failures of this test during Fedora builds which I think is down to the comparison being done before the output has been generated because of this typo...
> Fix typo in test dependency

- include/osmium/relations/members_database.hpp
Hello! I get an error due to include:
```cpp
#include <contrib/libs/libosmium/include/osmium/relations/relations_manager.hpp>
```
I use Ubuntu 20.04.1 LTS, clang version 12.0.1, libosmium version 2.17.0.
```bash
In file included from /contrib/libs/libosmium/include/osmium/relations/relations_manager.hpp:45:
/contrib/libs/libosmium/include/osmium/relations/members_database.hpp:162:55: error: 'osmium::iterator_range<osmium::relations::MembersDatabaseCommon::element *>::iterator' (aka 'osmium::relations::MembersDatabaseCommon::element *') is not a class, namespace, or enumeration
static typename iterator_range<iterator>::iterator::difference_type count_not_removed(const iterator_range<iterator>& range) noexcept {
^
1 error generated.
Failed
```
So I make PR to fix this problem.
> Fix return type.

- test/t/io/test_bzip2.cpp
Other than glibc, the musl standard C library does not check the
validity of file descriptors passed to `fdopen()`, so the constructor
of the (de)compressor does not throw an excption on musl-based systems.
Rather, an exception is thrown later, when the opened file is being used.
According to the musl team, the current musl behavior conforms to the POSIX
specification, and application code should be made agnostic to whether
or not the standard C library happens to validate file descriptors
passed to `fdopen()`.
After this change, all libosmium tests (including those for bzip2) are
passing on Alpine Linux, which uses musl as its standard C library.
Fixes https://github.com/osmcode/libosmium/issues/353.
> Make bzip2 unit tests pass on musl-based systems

- include/osmium/io/detail/read_write.hpp
- include/osmium/io/reader.hpp
I see nothing which would prevent posix_fadvise from working on FreeBSD (or in fact all systems which have it, suggest to add cmake check) as well.
Not really tested (I do not use osmium), but build and tests pass.
> Enable posix_fadvise usage on FreeBSD

- include/osmium/io/detail/pbf_input_format.hpp
- include/osmium/io/detail/read_write.hpp
- include/osmium/util/file.hpp
- test/CMakeLists.txt
- test/t/io/test_file_seek.cpp
This PR:
- Extracts the private method `osmium::io::detail::PbfParser::read_exactly` as a generic, easily reusable function
- Implements `osmium::util::file_seek` for random access in files (currently unused, see below)
- Tests the seek feature (which also uses `read_exactly`)
This works toward #367, which is where `file_seek` will be very useful.
If you think `file_seek` should instead live in `experimental`, I'd be happy to move the function there.
> Implement and test file seek, extract common "read_exactly" for reuse

- .github/ISSUE_TEMPLATE/config.yml
https://help.openstreetmap.org/ has "NOTICE: help.openstreetmap.org is no longer in use from 1st March 2024. Please use the OpenStreetMap Community Forum"
> replace dead site by official forum

- include/osmium/memory/collection.hpp
This fixes a compilation error where the `assert(.)` macro is not known:
```
#11 180.6 In file included from /src/third_party/libosmium/include/osmium/tags/filter.hpp:36,
#11 180.6                  from /src/include/extractor/restriction_parser.hpp:8,
#11 180.6                  from /src/src/extractor/restriction_parser.cpp:1:
#11 180.6 /src/third_party/libosmium/include/osmium/memory/collection.hpp: In instantiation of 'osmium::memory::CollectionFilterIterator<TFilter, TMember>& osmium::memory::CollectionFilterIterator<TFilter, TMember>::operator++() [with TFilter = osmium::tags::Filter<std::__cxx11::basic_string<char> >; TMember = const osmium::Tag]':
#11 180.6 /src/src/extractor/restriction_parser.cpp:101:34:   required from here
#11 180.6 …
```
> Include cassert in collection.hpp

- include/osmium/builder/osm_object_builder.hpp
- include/osmium/io/bzip2_compression.hpp
This PR fixes critical issues when processing global discussions files distributed by planet.osm.org, which contain changesets with comments. While libosmium can handle a large portion of the changesets, two issues would happen for some changesets.
Global discussions files (changesets with comments) from planet.osm.org such as discussions-20250519.osm.bz2 were not being processed successfully due to two issues:
1. **Incomplete file reading**: These files use multi-stream bzip2 compression, but libosmium was stopping after the first stream, causing incomplete XML tag error at some point.
2. **Memory corruption during parsing**: Comments in changesets could cause invalid memory reading when the number of comments goes high.
The tested inpiut file is …
> Fix handling of global discussions files from planet.osm.org
